[versions]
agp = "9.4.1"
appcompat = "1.8.0"
material = "1.14.0"
cardview = "1.0.0"
palette = "1.0.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
